"""RBIG: Rotation-Based Iterative Gaussianization."""

from rbig._src.base import (
    BaseITMeasure,
    BaseTransform,
    Bijector,
    CompositeBijector,
    MarginalBijector,
    RotationBijector,
)
from rbig._src.classify import RBIGBayesClassifier
from rbig._src.cluster import RBIGKMeans
from rbig._src.datasets import (
    make_banana,
    make_bimodal,
    make_cross,
    make_equicorrelated_gaussian,
    make_heavy_tail,
    make_rings,
    make_signal_plus_noise_dims,
    make_variance_leak,
    make_xor_labels,
)
from rbig._src.decomposition import RBIGReducer
from rbig._src.densities import (
    Cube,
    Exp,
    Tanh,
    bin_estimation,
    check_density,
    entropy_histogram,
    entropy_reduction,
    gaussian_entropy,
    generate_batches,
    joint_entropy_gaussian,
    kl_to_standard_normal,
    marginal_entropy,
    total_correlation,
)
from rbig._src.diagnostics import ResidualDiagnostics
from rbig._src.fairness import RBIGFairTransformer
from rbig._src.feature_selection import RBIGMISelector
from rbig._src.image import (
    DCTRotation,
    HartleyRotation,
    ImageBijector,
    ImageRBIG,
    OrthogonalWaveletLayer,
    RandomChannelRotation,
    WaveletTransform,
    extract_patches,
    matrix_to_patches,
    patches_to_matrix,
)
from rbig._src.marginal import (
    GMMGaussianizer,
    KDEGaussianizer,
    MarginalGaussianize,
    MarginalKDEGaussianize,
    MarginalUniformize,
    QuantileGaussianizer,
    SplineGaussianizer,
    make_cdf_monotonic,
)
from rbig._src.metrics import (
    entropy_marginal,
    entropy_normal_approx,
    entropy_quantile_spacing,
    entropy_rbig,
    entropy_univariate,
    information_reduction,
    information_summary,
    kl_divergence_rbig,
    mutual_information_rbig,
    negative_log_likelihood,
    negentropy,
    negentropy_kde,
    total_correlation_rbig,
)
from rbig._src.model import AnnealedRBIG, RBIGLayer
from rbig._src.outliers import RBIGOutlierDetector
from rbig._src.parametric import (
    BoxCoxTransform,
    LogitTransform,
    QuantileTransform,
    beta,
    dirichlet,
    entropy_gaussian,
    exponential,
    gamma,
    gaussian,
    kl_divergence_gaussian,
    laplace,
    lognormal,
    multivariate_gaussian,
    mutual_information_gaussian,
    student_t,
    total_correlation_gaussian,
    uniform,
    von_mises,
    wishart,
)
from rbig._src.rbig_measures import (
    InformationMeasures,
    entropy_rbig_reduction,
    estimate_cmi,
    estimate_dtc,
    estimate_entropy,
    estimate_interaction_information,
    estimate_jsd,
    estimate_kld,
    estimate_mi,
    estimate_o_information,
    estimate_tc,
    kl_divergence_rbig_reduction,
    mutual_information_rbig_reduction,
    pairwise_mi_matrix,
    total_correlation_rbig_reduction,
)
from rbig._src.rotation import (
    GaussianRandomProjection,
    ICARotation,
    OrthogonalDimensionalityReduction,
    PCARotation,
    PicardRotation,
    RandomOrthogonalProjection,
    RandomRotation,
)
from rbig._src.sliced import GIS, SIG, SIGLayer
from rbig._src.spline import RQSpline
from rbig._src.xarray_image import matrix_to_xr_image, xr_apply_rbig, xr_image_to_matrix
from rbig._src.xarray_st import (
    XarrayRBIG,
    matrix_to_xr_st,
    xr_rbig_fit_transform,
    xr_st_to_matrix,
)
from rbig._version import __version__

__all__ = [
    "GIS",
    "SIG",
    "AnnealedRBIG",
    "BaseITMeasure",
    "BaseTransform",
    "Bijector",
    "BoxCoxTransform",
    "CompositeBijector",
    "Cube",
    "DCTRotation",
    "Exp",
    "GMMGaussianizer",
    "GaussianRandomProjection",
    "HartleyRotation",
    "ICARotation",
    "ImageBijector",
    "ImageRBIG",
    "InformationMeasures",
    "KDEGaussianizer",
    "LogitTransform",
    "MarginalBijector",
    "MarginalGaussianize",
    "MarginalKDEGaussianize",
    "MarginalUniformize",
    "OrthogonalDimensionalityReduction",
    "OrthogonalWaveletLayer",
    "PCARotation",
    "PicardRotation",
    "QuantileGaussianizer",
    "QuantileTransform",
    "RBIGBayesClassifier",
    "RBIGFairTransformer",
    "RBIGKMeans",
    "RBIGLayer",
    "RBIGMISelector",
    "RBIGOutlierDetector",
    "RBIGReducer",
    "RQSpline",
    "RandomChannelRotation",
    "RandomOrthogonalProjection",
    "RandomRotation",
    "ResidualDiagnostics",
    "RotationBijector",
    "SIGLayer",
    "SplineGaussianizer",
    "Tanh",
    "WaveletTransform",
    "XarrayRBIG",
    "__version__",
    "beta",
    "bin_estimation",
    "check_density",
    "dirichlet",
    "entropy_gaussian",
    "entropy_histogram",
    "entropy_marginal",
    "entropy_normal_approx",
    "entropy_quantile_spacing",
    "entropy_rbig",
    "entropy_rbig_reduction",
    "entropy_reduction",
    "entropy_univariate",
    "estimate_cmi",
    "estimate_dtc",
    "estimate_entropy",
    "estimate_interaction_information",
    "estimate_jsd",
    "estimate_kld",
    "estimate_mi",
    "estimate_o_information",
    "estimate_tc",
    "exponential",
    "extract_patches",
    "gamma",
    "gaussian",
    "gaussian_entropy",
    "generate_batches",
    "information_reduction",
    "information_summary",
    "joint_entropy_gaussian",
    "kl_divergence_gaussian",
    "kl_divergence_rbig",
    "kl_divergence_rbig_reduction",
    "kl_to_standard_normal",
    "laplace",
    "lognormal",
    "make_banana",
    "make_bimodal",
    "make_cdf_monotonic",
    "make_cross",
    "make_equicorrelated_gaussian",
    "make_heavy_tail",
    "make_rings",
    "make_signal_plus_noise_dims",
    "make_variance_leak",
    "make_xor_labels",
    "marginal_entropy",
    "matrix_to_patches",
    "matrix_to_xr_image",
    "matrix_to_xr_st",
    "multivariate_gaussian",
    "mutual_information_gaussian",
    "mutual_information_rbig",
    "mutual_information_rbig_reduction",
    "negative_log_likelihood",
    "negentropy",
    "negentropy_kde",
    "pairwise_mi_matrix",
    "patches_to_matrix",
    "student_t",
    "total_correlation",
    "total_correlation_gaussian",
    "total_correlation_rbig",
    "total_correlation_rbig_reduction",
    "uniform",
    "von_mises",
    "wishart",
    "xr_apply_rbig",
    "xr_image_to_matrix",
    "xr_rbig_fit_transform",
    "xr_st_to_matrix",
]
